# Generated by Django 2.0.4 on 2018-04-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
    ]
