# Generated by Django 2.0.4 on 2018-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='url',
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.SlugField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
